function config = trainingConfig(task, dataset, options)
config = struct('task', task, 'dataset', struct('id', datasetID(dataset)), ...
    'model', struct('key', options.Model, 'parameters', options.ModelParameters), ...
    'training', options.Training, ...
    'execution', struct('device', options.Device, 'num_threads', options.NumThreads), ...
    'evaluation', struct('profile_id', options.Profile));
end
