import Alert from '@mui/material/Alert'
import Button from '@mui/material/Button'
import Dialog from '@mui/material/Dialog'
import DialogActions from '@mui/material/DialogActions'
import DialogContent from '@mui/material/DialogContent'
import DialogTitle from '@mui/material/DialogTitle'
import Stack from '@mui/material/Stack'
import TextField from '@mui/material/TextField'
import Typography from '@mui/material/Typography'
import { useState } from 'react'
import type { ExperimentConfigInput } from '@/api/types'
import { t } from '@/i18n'

/** Exported resolution metadata is regenerated by the service, never submitted as an editable field. */
export function importableConfig(data: unknown): ExperimentConfigInput {
  if (data === null || typeof data !== 'object' || Array.isArray(data)) throw new Error('expected a JSON object')
  const { resolution: _resolution, ...rest } = data as Record<string, unknown>
  const config = rest as ExperimentConfigInput
  if (typeof config.task !== 'string' || typeof config.dataset?.id !== 'string' || typeof config.model?.key !== 'string') throw new Error('task, dataset.id and model.key are required')
  return config
}

export function JsonConfigDialog({ config, onClose, onApply }: { config: ExperimentConfigInput | null; onClose: () => void; onApply: (config: ExperimentConfigInput, source: string) => void }) {
  const [draft, setDraft] = useState(JSON.stringify(config ?? {}, null, 2))
  const [source, setSource] = useState(t('json.edited'))
  const [error, setError] = useState('')
  const [reading, setReading] = useState(false)
  const load = async (file: File) => {
    setReading(true)
    try { setDraft(await file.text()); setSource(file.name); setError('') }
    catch (cause) { setError(String(cause)) }
    finally { setReading(false) }
  }
  return <Dialog open onClose={reading ? undefined : onClose} fullWidth maxWidth="md" aria-labelledby="json-config-title">
    <DialogTitle id="json-config-title">{t('json.title')}</DialogTitle>
    <DialogContent dividers><Stack spacing={2}>
      <Typography variant="body2" color="text.secondary">{t('json.help')}</Typography>
      <Button component="label" variant="outlined" disabled={reading} sx={{ alignSelf: 'flex-start' }}>{t('form.import')}<input hidden type="file" accept="application/json,.json" data-testid="import-config" onChange={(event) => { const file = event.target.files?.[0]; if (file) void load(file); event.target.value = '' }} /></Button>
      <TextField label={t('json.editor')} multiline minRows={12} maxRows={20} fullWidth value={draft} disabled={reading} onChange={(event) => { setDraft(event.target.value); setError('') }} slotProps={{ input: { sx: { fontFamily: 'monospace', fontSize: 13 } }, htmlInput: { spellCheck: false } }} />
      {error && <Alert severity="error">{t('form.import.invalid', { error })}</Alert>}
    </Stack></DialogContent>
    <DialogActions><Button onClick={onClose} disabled={reading}>{t('form.cancel')}</Button><Button variant="contained" disabled={reading} onClick={() => { try { onApply(importableConfig(JSON.parse(draft)), source) } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)) } }}>{t('json.apply')}</Button></DialogActions>
  </Dialog>
}
