/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/artifacts/{run_id}/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Artifact Download
         * @description Download by *registered id* only; paths are never accepted from clients.
         */
        get: operations["artifact_download_api_v1_artifacts__run_id___artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datasets List */
        get: operations["datasets_list_api_v1_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/import-builtin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dataset Import Builtin */
        post: operations["dataset_import_builtin_api_v1_datasets_import_builtin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dataset Get */
        get: operations["dataset_get_api_v1_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Experiments Validate
         * @description Resolve and bind without starting anything; config problems are data, not 4xx.
         */
        post: operations["experiments_validate_api_v1_experiments_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recipes */
        get: operations["recipes_api_v1_recipes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Results Get */
        get: operations["results_get_api_v1_results__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs List */
        get: operations["runs_list_api_v1_runs_get"];
        put?: never;
        /** Runs Submit */
        post: operations["runs_submit_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs Get */
        get: operations["runs_get_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs Artifacts */
        get: operations["runs_artifacts_api_v1_runs__run_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Runs Cancel */
        post: operations["runs_cancel_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs Config */
        get: operations["runs_config_api_v1_runs__run_id__config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events Stream
         * @description Server-Sent Events: ``id`` is the event seq; ``event: end`` closes a finished run.
         */
        get: operations["events_stream_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events List */
        get: operations["events_list_api_v1_runs__run_id__events_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Runs Logs
         * @description Page through logs/worker.log by byte offset (safe for very large logs).
         *
         *     A trailing line without newline is returned only once the run has finished
         *     (while running it may still be written).
         */
        get: operations["runs_logs_api_v1_runs__run_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Runs Retry */
        post: operations["runs_retry_api_v1_runs__run_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Info */
        get: operations["session_info_api_v1_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Session Bootstrap */
        post: operations["session_bootstrap_api_v1_session_bootstrap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_system_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Artifact */
        Artifact: {
            /** Artifact Id */
            artifact_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Description */
            description?: string | null;
            file: components["schemas"]["FileRef"];
            kind: components["schemas"]["ArtifactKind"];
            /**
             * Required
             * @default false
             */
            required: boolean;
        };
        /**
         * ArtifactKind
         * @enum {string}
         */
        ArtifactKind: "checkpoint" | "log_history" | "log_best" | "worker_log" | "dpd_output" | "plot" | "config" | "provenance" | "events" | "result" | "export" | "other";
        /** ArtifactManifest */
        ArtifactManifest: {
            /** Artifacts */
            artifacts?: components["schemas"]["Artifact"][];
            /**
             * Complete
             * @default false
             */
            complete: boolean;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
        };
        /**
         * BetterDirection
         * @enum {string}
         */
        BetterDirection: "lower" | "higher";
        /** BootstrapRequest */
        BootstrapRequest: {
            /** Token */
            token: string;
        };
        /** Capabilities */
        Capabilities: {
            /** Devices */
            devices: components["schemas"]["DeviceInfo"][];
            /** Note */
            note: string;
            /** Version */
            version: string;
            /** Workspace */
            workspace: string;
        };
        /** DPDReference */
        DPDReference: {
            /** Checkpoint Artifact Id */
            checkpoint_artifact_id?: string | null;
            /** Checkpoint Sha256 */
            checkpoint_sha256?: string | null;
            model?: components["schemas"]["ModelSpec"] | null;
            /** Run Id */
            run_id: string;
        };
        /** DatasetEvidence */
        DatasetEvidence: {
            /** Dataset Id */
            dataset_id: string;
            /** N Samples */
            n_samples?: number | null;
            /** Preprocessing Version */
            preprocessing_version: string;
            /** Processed Sha256 */
            processed_sha256?: string | null;
            /** Raw Sha256 */
            raw_sha256?: string | null;
            /**
             * Split
             * @enum {string}
             */
            split: "train" | "val" | "test";
            /** Split Version */
            split_version: string;
        };
        /** DatasetManifest */
        DatasetManifest: {
            /** Columns */
            columns?: {
                [key: string]: string;
            } | null;
            /** Dataset Id */
            dataset_id: string;
            /** Display Name */
            display_name: string;
            /** Files */
            files?: components["schemas"]["FileRef"][];
            /** N Samples */
            n_samples?: number | null;
            /** Notes */
            notes?: string | null;
            origin: components["schemas"]["DatasetOrigin"];
            /**
             * Preprocessing Version
             * @default raw-v1
             */
            preprocessing_version: string;
            /** Raw Sha256 */
            raw_sha256?: string | null;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /**
             * @default {
             *       "amplitude_units": "unknown"
             *     }
             */
            signal: components["schemas"]["SignalSpec"];
            source: components["schemas"]["DatasetSource"];
            split: components["schemas"]["SplitSpec"];
        };
        /**
         * DatasetOrigin
         * @enum {string}
         */
        DatasetOrigin: "measured" | "synthetic" | "unknown";
        /** DatasetRef */
        DatasetRef: {
            /** Id */
            id: string;
            /**
             * Preprocessing Version
             * @default raw-v1
             */
            preprocessing_version: string;
            /**
             * Split Version
             * @default contiguous-v1
             */
            split_version: string;
        };
        /** DatasetSource */
        DatasetSource: {
            /**
             * Imported At
             * Format: date-time
             */
            imported_at?: string;
            kind: components["schemas"]["DatasetSourceKind"];
            /** Name */
            name?: string | null;
            /** Original Path */
            original_path?: string | null;
        };
        /**
         * DatasetSourceKind
         * @enum {string}
         */
        DatasetSourceKind: "builtin" | "csv_import" | "numpy_import" | "legacy_dir_import";
        /** DeviceInfo */
        DeviceInfo: {
            /**
             * Count
             * @default 0
             */
            count: number;
            /** Detected */
            detected: boolean;
            /** Device */
            device: string;
            /** Name */
            name?: string | null;
            /** Tested Models */
            tested_models?: string[];
        };
        /** EvaluationConfig */
        EvaluationConfig: {
            /** Checkpoint Selection Metric */
            checkpoint_selection_metric?: string | null;
            evidence_type: components["schemas"]["EvidenceType"];
            /**
             * Profile Id
             * @default legacy-opendpd-v1
             */
            profile_id: string;
        };
        /** EvaluationResult */
        EvaluationResult: {
            dataset: components["schemas"]["DatasetEvidence"];
            /** Device */
            device: string;
            evidence_type: components["schemas"]["EvidenceType"];
            /** Extra */
            extra?: {
                [key: string]: number | string | boolean;
            };
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            history?: components["schemas"]["FileRef"] | null;
            /**
             * Is Mock
             * @default false
             */
            is_mock: boolean;
            /** Limitations */
            limitations?: string[];
            /** Metric Profile Id */
            metric_profile_id: string;
            /** Metric Profile Version */
            metric_profile_version: number;
            /** Metrics */
            metrics: components["schemas"]["MetricValue"][];
            /** Models */
            models?: components["schemas"]["ModelEvidence"][];
            /** N Segments */
            n_segments?: number | null;
            /** Nperseg */
            nperseg?: number | null;
            /**
             * Numeric Mode
             * @default float32
             */
            numeric_mode: string;
            reference: components["schemas"]["SignalReference"];
            /** Result Id */
            result_id: string;
            /** Run Id */
            run_id?: string | null;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Seed */
            seed?: number | null;
            /** Selected Epoch */
            selected_epoch?: number | null;
            software: components["schemas"]["SoftwareProvenance"];
            /**
             * Source
             * @enum {string}
             */
            source: "opendpd-studio" | "legacy-log-import" | "mock";
            /** Valid Sample Range */
            valid_sample_range?: [
                number,
                number
            ] | null;
        };
        /** EventPage */
        EventPage: {
            /** Events */
            events: components["schemas"]["RunEvent"][];
            /** Last Seq */
            last_seq: number;
            /** Terminal */
            terminal: boolean;
        };
        /**
         * EvidenceType
         * @description What kind of evidence a result represents. Never inferred, always declared.
         * @enum {string}
         */
        EvidenceType: "pa_modeling" | "dpd_surrogate" | "dpd_measured";
        /** ExecutionConfig */
        ExecutionConfig: {
            /**
             * Cuda Graph Training
             * @default false
             */
            cuda_graph_training: boolean;
            /**
             * Device
             * @default cpu
             * @enum {string}
             */
            device: "cpu" | "cuda" | "mps";
            /**
             * Device Index
             * @default 0
             */
            device_index: number;
            /** Num Threads */
            num_threads?: number | null;
        };
        /** ExperimentConfig */
        ExperimentConfig: {
            dataset: components["schemas"]["DatasetRef"];
            dpd_reference?: components["schemas"]["DPDReference"] | null;
            evaluation: components["schemas"]["EvaluationConfig"];
            execution?: components["schemas"]["ExecutionConfig"];
            model: components["schemas"]["ModelSpec"];
            /** Name */
            name?: string | null;
            /** Notes */
            notes?: string | null;
            pa_reference?: components["schemas"]["PAReference"] | null;
            quantization?: components["schemas"]["QuantizationConfig"] | null;
            /** Recipe Id */
            recipe_id?: string | null;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            task: components["schemas"]["TaskType"];
            training?: components["schemas"]["TrainingConfig"];
        };
        /**
         * FileRef
         * @description A file inside a known container (workspace, run or dataset directory).
         *     Paths are relative POSIX paths; absolute paths and ``..`` are rejected so
         *     a manifest can never point outside its container.
         */
        FileRef: {
            /** Path */
            path: string;
            /** Sha256 */
            sha256?: string | null;
            /** Size Bytes */
            size_bytes?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportBuiltinRequest */
        ImportBuiltinRequest: {
            /** Dataset Id */
            dataset_id?: string | null;
            /** Name */
            name: string;
        };
        /** LogPage */
        LogPage: {
            /** Eof */
            eof: boolean;
            /** Lines */
            lines: string[];
            /** Next Offset */
            next_offset: number;
            /** Size */
            size: number;
        };
        /**
         * MetricStatus
         * @enum {string}
         */
        MetricStatus: "ok" | "not_applicable" | "missing_reference" | "invalid" | "failed";
        /**
         * MetricValue
         * @description One formal metric. ``value`` is only present when ``status`` is ``ok``
         *     and is always finite; every other status carries a reason. This is how
         *     "null / not applicable / failed / infinite" get explicit meanings and how
         *     zero-filling of missing metrics is made impossible.
         */
        MetricValue: {
            better: components["schemas"]["BetterDirection"];
            /** Name */
            name: string;
            /** Reason */
            reason?: string | null;
            /** @default ok */
            status: components["schemas"]["MetricStatus"];
            /** Unit */
            unit: string;
            /** Value */
            value?: number | null;
        };
        /** ModelEvidence */
        ModelEvidence: {
            /**
             * Execution Semantics
             * @default offline_segmented
             */
            execution_semantics: string;
            /** Lookahead Samples */
            lookahead_samples?: number | null;
            model: components["schemas"]["ModelSpec"];
            /** N Parameters */
            n_parameters?: number | null;
            /**
             * Role
             * @enum {string}
             */
            role: "pa" | "dpd";
            /** Run Id */
            run_id?: string | null;
            /** Weights Sha256 */
            weights_sha256?: string | null;
        };
        /**
         * ModelInfo
         * @description Registry descriptor as seen by clients (opendpd.core.registry.ModelDescriptor).
         */
        ModelInfo: {
            /** Constraints */
            constraints?: string | null;
            /** Devices Tested */
            devices_tested: string[];
            /** Display Name */
            display_name: string;
            /** Evidence */
            evidence?: string | null;
            /** Execution Semantics */
            execution_semantics: string;
            /** Export Formats */
            export_formats: string[];
            /** Family */
            family: string;
            /** Key */
            key: string;
            /** Legacy Backbone */
            legacy_backbone: string;
            /** Lookahead Note */
            lookahead_note: string;
            /** Lookahead Samples */
            lookahead_samples?: number | null;
            /** Params */
            params: components["schemas"]["ParamSpecInfo"][];
            /** Reference */
            reference?: string | null;
            /** Roles */
            roles: string[];
            /** Status */
            status: string;
            /** Training Method */
            training_method: string;
        };
        /** ModelSpec */
        ModelSpec: {
            /** Key */
            key: string;
            /** Parameters */
            parameters?: {
                [key: string]: number | string | boolean;
            };
        };
        /**
         * PAReference
         * @description The frozen PA surrogate a DPD task trains or evaluates through.
         */
        PAReference: {
            /** Checkpoint Artifact Id */
            checkpoint_artifact_id?: string | null;
            /** Checkpoint Sha256 */
            checkpoint_sha256?: string | null;
            model?: components["schemas"]["ModelSpec"] | null;
            /** Run Id */
            run_id: string;
        };
        /** ParamSpecInfo */
        ParamSpecInfo: {
            /** Choices */
            choices?: unknown[] | null;
            /** Default */
            default: unknown;
            /** Description */
            description: string;
            /** Legacy Arg */
            legacy_arg?: {
                [key: string]: string;
            };
            /** Maximum */
            maximum?: number | null;
            /** Minimum */
            minimum?: number | null;
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /** QuantizationConfig */
        QuantizationConfig: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * N Bits A
             * @default 8
             */
            n_bits_a: number;
            /**
             * N Bits W
             * @default 8
             */
            n_bits_w: number;
            /** Pretrained Run Id */
            pretrained_run_id?: string | null;
        };
        /** RecipeInfo */
        RecipeInfo: {
            /** Description */
            description: string;
            /** Expected Duration */
            expected_duration: string;
            /** Limits */
            limits: string;
            model: components["schemas"]["ModelSpec"];
            /** Purpose */
            purpose: string;
            /** Recipe Id */
            recipe_id: string;
            task: components["schemas"]["TaskType"];
            /** Title */
            title: string;
            training: components["schemas"]["TrainingConfig"];
        };
        /** ResolutionInfo */
        ResolutionInfo: {
            /** Config Sha256 */
            config_sha256: string;
            /** Defaults Source */
            defaults_source: string;
            /**
             * Resolved At
             * Format: date-time
             */
            resolved_at?: string;
            /** Resolver Version */
            resolver_version: string;
            /** Warnings */
            warnings?: string[];
        };
        /**
         * ResolvedExperimentConfig
         * @description Same shape as ``ExperimentConfig`` but every result-affecting default is
         *     explicit, model parameters are complete, and the checkpoint selection
         *     metric is set. Produced only by ``opendpd.services.config.resolve``.
         */
        ResolvedExperimentConfig: {
            dataset: components["schemas"]["DatasetRef"];
            dpd_reference?: components["schemas"]["DPDReference"] | null;
            evaluation: components["schemas"]["EvaluationConfig"];
            execution?: components["schemas"]["ExecutionConfig"];
            model: components["schemas"]["ModelSpec"];
            /** Name */
            name?: string | null;
            /** Notes */
            notes?: string | null;
            pa_reference?: components["schemas"]["PAReference"] | null;
            quantization?: components["schemas"]["QuantizationConfig"] | null;
            /** Recipe Id */
            recipe_id?: string | null;
            resolution: components["schemas"]["ResolutionInfo"];
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            task: components["schemas"]["TaskType"];
            training?: components["schemas"]["TrainingConfig"];
        };
        /** RunError */
        RunError: {
            /** Code */
            code: string;
            /** Hint */
            hint?: string | null;
            /** Message */
            message: string;
            /** Stage */
            stage?: string | null;
            /** Traceback Tail */
            traceback_tail?: string | null;
        };
        /**
         * RunEvent
         * @description Append-only, strictly increasing ``seq`` per run. Clients resume from
         *     the last ``seq`` they saw; when the server can no longer replay from that
         *     point it answers with a snapshot requirement instead of guessing.
         */
        RunEvent: {
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            type: components["schemas"]["RunEventType"];
        };
        /**
         * RunEventType
         * @enum {string}
         */
        RunEventType: "status" | "progress" | "metric" | "log" | "artifact" | "checkpoint" | "heartbeat" | "error";
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "succeeded" | "failed" | "cancel_requested" | "cancelled" | "interrupted";
        /** RunView */
        RunView: {
            /** Config Sha256 */
            config_sha256?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dataset Id */
            dataset_id?: string | null;
            /** Device */
            device?: string | null;
            error?: components["schemas"]["RunError"] | null;
            /** Exit Code */
            exit_code?: number | null;
            /** Experiment Id */
            experiment_id?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Heartbeat Stale
             * @default false
             */
            heartbeat_stale: boolean;
            /** Idempotency Key */
            idempotency_key?: string | null;
            /**
             * Last Event Seq
             * @default 0
             */
            last_event_seq: number;
            /** Last Heartbeat At */
            last_heartbeat_at?: string | null;
            /** Model Key */
            model_key?: string | null;
            /** Name */
            name?: string | null;
            /** Parent Run Id */
            parent_run_id?: string | null;
            /** Progress Epoch */
            progress_epoch?: number | null;
            /** Progress Total Epochs */
            progress_total_epochs?: number | null;
            /** Result Id */
            result_id?: string | null;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["RunStatus"];
            /** Status Reason */
            status_reason?: string | null;
            task: components["schemas"]["TaskType"];
            worker?: components["schemas"]["WorkerInfo"] | null;
        };
        /** SessionInfo */
        SessionInfo: {
            /** Authenticated */
            authenticated: boolean;
            /** Csrf Token */
            csrf_token?: string | null;
            /**
             * Version
             * @default 2.2.0.dev0
             */
            version: string;
        };
        /**
         * SignalReference
         * @description What the evaluated signal was compared against.
         */
        SignalReference: {
            /** Description */
            description: string;
            /** Gain Rule */
            gain_rule?: string | null;
            /** Gain Value */
            gain_value?: number | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "linear_gain_target" | "measured_pa_output" | "pa_surrogate_output";
        };
        /**
         * SignalSpec
         * @description Signal metadata needed by evaluation profiles. Unknown values stay
         *     ``None``; they are never guessed. ``missing_for_legacy_evaluation`` names
         *     what the legacy profile still needs.
         */
        SignalSpec: {
            /**
             * Amplitude Units
             * @default unknown
             * @enum {string}
             */
            amplitude_units: "normalized" | "volts" | "unknown";
            /** Bandwidth Hz */
            bandwidth_hz?: number | null;
            /** Modulation */
            modulation?: string | null;
            /** N Sub Ch */
            n_sub_ch?: number | null;
            /** Nperseg */
            nperseg?: number | null;
            /** Sample Rate Hz */
            sample_rate_hz?: number | null;
            /** Standard */
            standard?: string | null;
            /** Sub Channel Bandwidth Hz */
            sub_channel_bandwidth_hz?: number | null;
        };
        /** SoftwareProvenance */
        SoftwareProvenance: {
            /** Git Commit */
            git_commit?: string | null;
            /** Git Dirty */
            git_dirty?: boolean | null;
            /** Opendpd Version */
            opendpd_version: string;
            /** Platform */
            platform: string;
            /** Python Version */
            python_version: string;
            /** Torch Version */
            torch_version?: string | null;
        };
        /**
         * SplitSpec
         * @description Contiguous train/val/test split performed *before* framing, with an
         *     optional guard band so overlapping frames never straddle a boundary.
         */
        SplitSpec: {
            /** Boundaries */
            boundaries?: {
                [key: string]: [
                    number,
                    number
                ];
            } | null;
            /**
             * Guard Samples
             * @default 0
             */
            guard_samples: number;
            /**
             * Method
             * @default contiguous
             * @constant
             */
            method: "contiguous";
            /** Ratios */
            ratios: {
                [key: string]: number;
            };
            /**
             * Version
             * @default contiguous-v1
             */
            version: string;
        };
        /** SubmitRunRequest */
        SubmitRunRequest: {
            config: components["schemas"]["ExperimentConfig"];
            /** Idempotency Key */
            idempotency_key?: string | null;
            /** Name */
            name?: string | null;
        };
        /**
         * TaskType
         * @enum {string}
         */
        TaskType: "train_pa" | "train_dpd" | "run_dpd";
        /**
         * TrainingConfig
         * @description Defaults mirror the OpenDPDv2 recipe (arguments.py); they are the
         *     single source of defaults for every entry point.
         */
        TrainingConfig: {
            /**
             * Batch Size
             * @default 64
             */
            batch_size: number;
            /**
             * Batch Size Eval
             * @default 64
             */
            batch_size_eval: number;
            /**
             * Decay Factor
             * @default 0.5
             */
            decay_factor: number;
            /**
             * Epochs
             * @default 300
             */
            epochs: number;
            /**
             * Eval Test
             * @default true
             */
            eval_test: boolean;
            /**
             * Eval Val
             * @default true
             */
            eval_val: boolean;
            /**
             * Frame Length
             * @default 200
             */
            frame_length: number;
            /**
             * Frame Stride
             * @default 1
             */
            frame_stride: number;
            /**
             * Grad Clip
             * @default 200
             */
            grad_clip: number;
            /**
             * Learning Rate
             * @default 0.005
             */
            learning_rate: number;
            /**
             * Loss
             * @default l2
             * @enum {string}
             */
            loss: "l2" | "l1";
            /**
             * Lr End
             * @default 0.00005
             */
            lr_end: number;
            /**
             * Lr Schedule
             * @default true
             */
            lr_schedule: boolean;
            /**
             * Optimizer
             * @default adamw
             * @enum {string}
             */
            optimizer: "adamw" | "adam" | "sgd" | "rmsprop";
            /**
             * Patience
             * @default 5
             */
            patience: number;
            /**
             * Reproducibility
             * @default soft
             * @enum {string}
             */
            reproducibility: "soft" | "hard";
            /**
             * Seed
             * @default 0
             */
            seed: number;
        };
        /** ValidateRequest */
        ValidateRequest: {
            /** Config */
            config: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkerInfo
         * @description Identity of the worker process. PID alone is never trusted: the
         *     process creation time must match too (PIDs are recycled).
         */
        WorkerInfo: {
            /** Create Time */
            create_time: number;
            /** Host */
            host: string;
            /** Pid */
            pid: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    artifact_download_api_v1_artifacts__run_id___artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    datasets_list_api_v1_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetManifest"][];
                };
            };
        };
    };
    dataset_import_builtin_api_v1_datasets_import_builtin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportBuiltinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetManifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_get_api_v1_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetManifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    experiments_validate_api_v1_experiments_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfo"][];
                };
            };
        };
    };
    recipes_api_v1_recipes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeInfo"][];
                };
            };
        };
    };
    results_get_api_v1_results__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_list_api_v1_runs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["RunStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_submit_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_get_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_artifacts_api_v1_runs__run_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactManifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_cancel_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_config_api_v1_runs__run_id__config_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedExperimentConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_stream_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_list_api_v1_runs__run_id__events_list_get: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_logs_api_v1_runs__run_id__logs_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_retry_api_v1_runs__run_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_info_api_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
        };
    };
    session_bootstrap_api_v1_session_bootstrap_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BootstrapRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_api_v1_system_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
}
