/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/artifacts/{run_id}/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Artifact Download
         * @description Download by *registered id* only; paths are never accepted from clients.
         */
        get: operations["artifact_download_api_v1_artifacts__run_id___artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Datasets List */
        get: operations["datasets_list_api_v1_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dataset Import */
        post: operations["dataset_import_api_v1_datasets_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/import-builtin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dataset Import Builtin */
        post: operations["dataset_import_builtin_api_v1_datasets_import_builtin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/import-roots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Import Roots */
        get: operations["import_roots_api_v1_datasets_import_roots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/import-roots/{root_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Import Root Files */
        get: operations["import_root_files_api_v1_datasets_import_roots__root_id__files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dataset Inspect */
        post: operations["dataset_inspect_api_v1_datasets_inspect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dataset Upload
         * @description Browser upload, streamed into <workspace>/imports/uploads (then imported like any root file).
         */
        post: operations["dataset_upload_api_v1_datasets_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dataset Get */
        get: operations["dataset_get_api_v1_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dataset Diagnostics Latest */
        get: operations["dataset_diagnostics_latest_api_v1_datasets__dataset_id__diagnostics_get"];
        put?: never;
        /** Dataset Diagnostics Run */
        post: operations["dataset_diagnostics_run_api_v1_datasets__dataset_id__diagnostics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dataset Update */
        post: operations["dataset_update_api_v1_datasets__dataset_id__manifest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/preprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dataset Preprocess */
        post: operations["dataset_preprocess_api_v1_datasets__dataset_id__preprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/preprocess/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dataset Preprocess Preview */
        post: operations["dataset_preprocess_preview_api_v1_datasets__dataset_id__preprocess_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Experiments Validate
         * @description Resolve and bind without starting anything; config problems are data, not 4xx.
         */
        post: operations["experiments_validate_api_v1_experiments_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metric Profiles
         * @description Every registered metric profile: the definition behind each score.
         */
        get: operations["metric_profiles_api_v1_metrics_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metric Profile */
        get: operations["metric_profile_api_v1_metrics_profiles__profile_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recipes */
        get: operations["recipes_api_v1_recipes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Results Compare
         * @description Stored results side by side with the protocol differences that forbid ranking. `format=csv` returns the
         *     same numbers with their provenance rows; nothing is recomputed.
         */
        get: operations["results_compare_api_v1_results_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Results Get */
        get: operations["results_get_api_v1_results__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/{run_id}/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Results Profiles
         * @description Metric profiles under which this run has a stored result (primary first).
         */
        get: operations["results_profiles_api_v1_results__run_id__profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs List */
        get: operations["runs_list_api_v1_runs_get"];
        put?: never;
        /** Runs Submit */
        post: operations["runs_submit_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs Get */
        get: operations["runs_get_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs Artifacts */
        get: operations["runs_artifacts_api_v1_runs__run_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Runs Cancel */
        post: operations["runs_cancel_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs Config */
        get: operations["runs_config_api_v1_runs__run_id__config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events Stream
         * @description Server-Sent Events: ``id`` is the event seq; ``event: end`` closes a finished run.
         */
        get: operations["events_stream_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events List */
        get: operations["events_list_api_v1_runs__run_id__events_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Runs History
         * @description Per-epoch validation / test metrics from the run's history log (the same shape as `metric` events).
         */
        get: operations["runs_history_api_v1_runs__run_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Runs Lineage
         * @description The experiment graph around a run: PA surrogate, DPD model and retry links with the checkpoint hashes used.
         */
        get: operations["runs_lineage_api_v1_runs__run_id__lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Runs Logs
         * @description Page through logs/worker.log by byte offset (safe for very large logs).
         *
         *     A trailing line without newline is returned only once the run has finished
         *     (while running it may still be written).
         */
        get: operations["runs_logs_api_v1_runs__run_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Runs Retry */
        post: operations["runs_retry_api_v1_runs__run_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Info */
        get: operations["session_info_api_v1_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Session Bootstrap */
        post: operations["session_bootstrap_api_v1_session_bootstrap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_system_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Artifact */
        Artifact: {
            /** Artifact Id */
            artifact_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Description */
            description?: string | null;
            file: components["schemas"]["FileRef"];
            kind: components["schemas"]["ArtifactKind"];
            /**
             * Required
             * @default false
             */
            required: boolean;
        };
        /**
         * ArtifactKind
         * @enum {string}
         */
        ArtifactKind: "checkpoint" | "log_history" | "log_best" | "worker_log" | "dpd_output" | "plot" | "config" | "provenance" | "events" | "result" | "export" | "other";
        /** ArtifactManifest */
        ArtifactManifest: {
            /** Artifacts */
            artifacts?: components["schemas"]["Artifact"][];
            /**
             * Complete
             * @default false
             */
            complete: boolean;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
        };
        /**
         * BaselineScore
         * @description Scores of a comparison signal under the *same* reference, profile and
         *     valid range as ``EvaluationResult.metrics``; never normalised separately.
         */
        BaselineScore: {
            /** Description */
            description: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "surrogate_without_dpd" | "measured_without_dpd";
            /** Metrics */
            metrics: components["schemas"]["MetricValue"][];
        };
        /**
         * BetterDirection
         * @enum {string}
         */
        BetterDirection: "lower" | "higher";
        /** Body_dataset_upload_api_v1_datasets_upload_post */
        Body_dataset_upload_api_v1_datasets_upload_post: {
            /** File */
            file: string;
        };
        /** BootstrapRequest */
        BootstrapRequest: {
            /** Token */
            token: string;
        };
        /** Capabilities */
        Capabilities: {
            /** Devices */
            devices: components["schemas"]["DeviceInfo"][];
            /** Note */
            note: string;
            /** Version */
            version: string;
            /** Workspace */
            workspace: string;
        };
        /** ComparisonPair */
        ComparisonPair: {
            /** A */
            a: string;
            /** B */
            b: string;
            /** Incompatibilities */
            incompatibilities?: string[];
        };
        /**
         * ComparisonReport
         * @description Results shown side by side. ``comparable`` is True only when every pair was produced under the same
         *     protocol (``opendpd.core.metrics.incompatibilities``); otherwise the reasons are listed and nothing is ranked.
         */
        ComparisonReport: {
            /** Comparable */
            comparable: boolean;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /** Note */
            note: string;
            /** Pairs */
            pairs?: components["schemas"]["ComparisonPair"][];
            /** Results */
            results: components["schemas"]["EvaluationResult"][];
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
        };
        /** DPDReference */
        DPDReference: {
            /** Checkpoint Artifact Id */
            checkpoint_artifact_id?: string | null;
            /** Checkpoint Sha256 */
            checkpoint_sha256?: string | null;
            model?: components["schemas"]["ModelSpec"] | null;
            /** Run Id */
            run_id: string;
        };
        /** DatasetEvidence */
        DatasetEvidence: {
            /** Dataset Id */
            dataset_id: string;
            /** N Samples */
            n_samples?: number | null;
            /** Preprocessing Version */
            preprocessing_version: string;
            /** Processed Sha256 */
            processed_sha256?: string | null;
            /** Raw Sha256 */
            raw_sha256?: string | null;
            /**
             * Split
             * @enum {string}
             */
            split: "train" | "val" | "test";
            /** Split Version */
            split_version: string;
        };
        /** DatasetManifest */
        DatasetManifest: {
            /** Columns */
            columns?: {
                [key: string]: string;
            } | null;
            /** Dataset Id */
            dataset_id: string;
            /** Display Name */
            display_name: string;
            /** Files */
            files?: components["schemas"]["FileRef"][];
            /** N Samples */
            n_samples?: number | null;
            /** Notes */
            notes?: string | null;
            origin: components["schemas"]["DatasetOrigin"];
            /**
             * Preprocessing Version
             * @default raw-v1
             */
            preprocessing_version: string;
            /** Raw Sha256 */
            raw_sha256?: string | null;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /**
             * @default {
             *       "amplitude_units": "unknown"
             *     }
             */
            signal: components["schemas"]["SignalSpec"];
            source: components["schemas"]["DatasetSource"];
            split: components["schemas"]["SplitSpec"];
            /** Versions */
            versions?: components["schemas"]["DatasetVersion"][];
        };
        /**
         * DatasetOrigin
         * @enum {string}
         */
        DatasetOrigin: "measured" | "synthetic" | "unknown";
        /** DatasetRef */
        DatasetRef: {
            /** Id */
            id: string;
            /**
             * Preprocessing Version
             * @default raw-v1
             */
            preprocessing_version: string;
            /**
             * Split Version
             * @default contiguous-v1
             */
            split_version: string;
        };
        /** DatasetSource */
        DatasetSource: {
            /**
             * Imported At
             * Format: date-time
             */
            imported_at?: string;
            kind: components["schemas"]["DatasetSourceKind"];
            /** Name */
            name?: string | null;
            /** Original Path */
            original_path?: string | null;
        };
        /**
         * DatasetSourceKind
         * @enum {string}
         */
        DatasetSourceKind: "builtin" | "csv_import" | "numpy_import" | "legacy_dir_import";
        /**
         * DatasetVersion
         * @description One materialised data version (raw-v1 or a preprocessing result), in the
         *     directory layout the trainer reads (split CSV files).
         */
        DatasetVersion: {
            /** Base Version */
            base_version?: string | null;
            /** Code Version */
            code_version?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Files */
            files?: components["schemas"]["FileRef"][];
            /** Fit Range */
            fit_range?: [
                number,
                number
            ] | null;
            /** N Samples */
            n_samples: number;
            params?: components["schemas"]["PreprocessingParams"] | null;
            /** Record */
            record?: {
                [key: string]: unknown;
            };
            /** Sha256 */
            sha256?: string | null;
            split: components["schemas"]["SplitSpec"];
            /** Version */
            version: string;
        };
        /** DeviceInfo */
        DeviceInfo: {
            /**
             * Count
             * @default 0
             */
            count: number;
            /** Detected */
            detected: boolean;
            /** Device */
            device: string;
            /** Name */
            name?: string | null;
            /** Tested Models */
            tested_models?: string[];
        };
        /** DiagnosticItem */
        DiagnosticItem: {
            /**
             * Blocking
             * @default false
             */
            blocking: boolean;
            /** Code */
            code: string;
            /** Confidence */
            confidence?: number | null;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
            severity: components["schemas"]["Severity"];
            /** Suggestion */
            suggestion?: string | null;
            /** Title */
            title: string;
        };
        /** DiagnosticReport */
        DiagnosticReport: {
            /** Dataset Id */
            dataset_id: string;
            /** Dataset Raw Sha256 */
            dataset_raw_sha256?: string | null;
            /**
             * Doctor Version
             * @default dataset-doctor-v1
             */
            doctor_version: string;
            /**
             * Evaluation Blocked
             * @default false
             */
            evaluation_blocked: boolean;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /** Items */
            items?: components["schemas"]["DiagnosticItem"][];
            /** Report Id */
            report_id: string;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
        };
        /** EvaluationConfig */
        EvaluationConfig: {
            /** Checkpoint Selection Metric */
            checkpoint_selection_metric?: string | null;
            evidence_type?: components["schemas"]["EvidenceType"] | null;
            /**
             * Profile Id
             * @default legacy-opendpd-v1
             */
            profile_id: string;
        };
        /** EvaluationResult */
        EvaluationResult: {
            /** Baselines */
            baselines?: components["schemas"]["BaselineScore"][];
            dataset: components["schemas"]["DatasetEvidence"];
            /** Device */
            device: string;
            evidence_type: components["schemas"]["EvidenceType"];
            /** Extra */
            extra?: {
                [key: string]: number | string | boolean;
            };
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            history?: components["schemas"]["FileRef"] | null;
            /**
             * Is Mock
             * @default false
             */
            is_mock: boolean;
            /** Limitations */
            limitations?: string[];
            /** Metric Profile Id */
            metric_profile_id: string;
            /** Metric Profile Version */
            metric_profile_version: number;
            /** Metrics */
            metrics: components["schemas"]["MetricValue"][];
            /** Models */
            models?: components["schemas"]["ModelEvidence"][];
            /** N Segments */
            n_segments?: number | null;
            /** Nperseg */
            nperseg?: number | null;
            /**
             * Numeric Mode
             * @default float32
             */
            numeric_mode: string;
            reference: components["schemas"]["SignalReference"];
            /** Result Id */
            result_id: string;
            /** Run Id */
            run_id?: string | null;
            scaling?: components["schemas"]["ScalingInfo"] | null;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Seed */
            seed?: number | null;
            /** Selected Epoch */
            selected_epoch?: number | null;
            /** Signal Chain */
            signal_chain?: components["schemas"]["SignalStage"][];
            software: components["schemas"]["SoftwareProvenance"];
            /**
             * Source
             * @enum {string}
             */
            source: "opendpd-studio" | "legacy-log-import" | "mock";
            surrogate_coverage?: components["schemas"]["SurrogateCoverage"] | null;
            /** Valid Sample Range */
            valid_sample_range?: [
                number,
                number
            ] | null;
        };
        /** EventPage */
        EventPage: {
            /** Events */
            events: components["schemas"]["RunEvent"][];
            /** Last Seq */
            last_seq: number;
            /** Terminal */
            terminal: boolean;
        };
        /**
         * EvidenceType
         * @description What kind of evidence a result represents. Never inferred, always declared.
         * @enum {string}
         */
        EvidenceType: "pa_modeling" | "dpd_surrogate" | "dpd_measured";
        /** ExecutionConfig */
        ExecutionConfig: {
            /**
             * Cuda Graph Training
             * @default false
             */
            cuda_graph_training: boolean;
            /**
             * Device
             * @default cpu
             * @enum {string}
             */
            device: "cpu" | "cuda" | "mps";
            /**
             * Device Index
             * @default 0
             */
            device_index: number;
            /** Num Threads */
            num_threads?: number | null;
        };
        /** ExperimentConfig */
        ExperimentConfig: {
            dataset: components["schemas"]["DatasetRef"];
            dpd_reference?: components["schemas"]["DPDReference"] | null;
            evaluation?: components["schemas"]["EvaluationConfig"];
            execution?: components["schemas"]["ExecutionConfig"];
            model: components["schemas"]["ModelSpec"];
            /** Name */
            name?: string | null;
            /** Notes */
            notes?: string | null;
            pa_reference?: components["schemas"]["PAReference"] | null;
            quantization?: components["schemas"]["QuantizationConfig"] | null;
            /** Recipe Id */
            recipe_id?: string | null;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            task: components["schemas"]["TaskType"];
            training?: components["schemas"]["TrainingConfig"];
        };
        /** FileEntryInfo */
        FileEntryInfo: {
            /** Kind */
            kind: string;
            /** Path */
            path: string;
            /**
             * Size Bytes
             * @default 0
             */
            size_bytes: number;
        };
        /**
         * FileRef
         * @description A file inside a known container (workspace, run or dataset directory).
         *     Paths are relative POSIX paths; absolute paths and ``..`` are rejected so
         *     a manifest can never point outside its container.
         */
        FileRef: {
            /** Path */
            path: string;
            /** Sha256 */
            sha256?: string | null;
            /** Size Bytes */
            size_bytes?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryPoint
         * @description One split's metrics after one epoch, read from the run's history log (same shape as ``metric`` events).
         */
        HistoryPoint: {
            /** Epoch */
            epoch: number;
            /**
             * Split
             * @enum {string}
             */
            split: "val" | "test";
            /** Train Loss */
            train_loss?: number | null;
            /** Values */
            values?: {
                [key: string]: number;
            };
        };
        /** ImportBuiltinRequest */
        ImportBuiltinRequest: {
            /** Dataset Id */
            dataset_id?: string | null;
            /** Name */
            name: string;
        };
        /** ImportRequest */
        ImportRequest: {
            /** Dataset Id */
            dataset_id?: string | null;
            /** Display Name */
            display_name?: string | null;
            /**
             * Guard Samples
             * @default 256
             */
            guard_samples: number;
            /** Mapping */
            mapping?: {
                [key: string]: string;
            };
            /** Notes */
            notes?: string | null;
            /** @default unknown */
            origin: components["schemas"]["DatasetOrigin"];
            /**
             * @default {
             *       "amplitude_units": "unknown"
             *     }
             */
            signal: components["schemas"]["SignalSpec"];
            source: components["schemas"]["SourceRef"];
        };
        /** ImportRootInfo */
        ImportRootInfo: {
            /** Exists */
            exists: boolean;
            /** Path */
            path: string;
            /** Root Id */
            root_id: string;
        };
        /** LineageLink */
        LineageLink: {
            /** Checkpoint Sha256 */
            checkpoint_sha256?: string | null;
            relation: components["schemas"]["LineageRelation"];
            /** Run Id */
            run_id: string;
            status?: components["schemas"]["RunStatus"] | null;
            task?: components["schemas"]["TaskType"] | null;
        };
        /**
         * LineageRelation
         * @description How one run depends on another. Recorded from resolved configurations, never inferred from names.
         * @enum {string}
         */
        LineageRelation: "pa_surrogate" | "dpd_model" | "retry_of";
        /** LogPage */
        LogPage: {
            /** Eof */
            eof: boolean;
            /** Lines */
            lines: string[];
            /** Next Offset */
            next_offset: number;
            /** Size */
            size: number;
        };
        /** ManifestUpdate */
        ManifestUpdate: {
            /** Display Name */
            display_name?: string | null;
            /** Notes */
            notes?: string | null;
            origin?: components["schemas"]["DatasetOrigin"] | null;
            signal?: components["schemas"]["SignalSpec"] | null;
        };
        /** MetricDefinition */
        MetricDefinition: {
            /** Aggregation */
            aggregation: string;
            better: components["schemas"]["BetterDirection"];
            /** Display Name */
            display_name: string;
            /** Formula */
            formula: string;
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /**
             * Requires Reference
             * @default true
             */
            requires_reference: boolean;
            /** Unit */
            unit: string;
        };
        /** MetricProfile */
        MetricProfile: {
            /**
             * Deprecated
             * @default false
             */
            deprecated: boolean;
            /** Description */
            description: string;
            /**
             * Frozen
             * @default false
             */
            frozen: boolean;
            /** Metrics */
            metrics: components["schemas"]["MetricDefinition"][];
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            /** Profile Id */
            profile_id: string;
            /** Version */
            version: number;
        };
        /**
         * MetricStatus
         * @enum {string}
         */
        MetricStatus: "ok" | "not_applicable" | "missing_reference" | "invalid" | "failed";
        /**
         * MetricValue
         * @description One formal metric. ``value`` is only present when ``status`` is ``ok``
         *     and is always finite; every other status carries a reason. This is how
         *     "null / not applicable / failed / infinite" get explicit meanings and how
         *     zero-filling of missing metrics is made impossible.
         */
        MetricValue: {
            better: components["schemas"]["BetterDirection"];
            /** Name */
            name: string;
            /** Reason */
            reason?: string | null;
            /** @default ok */
            status: components["schemas"]["MetricStatus"];
            /** Unit */
            unit: string;
            /** Value */
            value?: number | null;
        };
        /** ModelEvidence */
        ModelEvidence: {
            /**
             * Execution Semantics
             * @default offline_segmented
             */
            execution_semantics: string;
            /** Lookahead Samples */
            lookahead_samples?: number | null;
            model: components["schemas"]["ModelSpec"];
            /** N Parameters */
            n_parameters?: number | null;
            /**
             * Role
             * @enum {string}
             */
            role: "pa" | "dpd";
            /** Run Id */
            run_id?: string | null;
            /** Weights Sha256 */
            weights_sha256?: string | null;
        };
        /**
         * ModelInfo
         * @description Registry descriptor as seen by clients (opendpd.core.registry.ModelDescriptor).
         */
        ModelInfo: {
            /** Constraints */
            constraints?: string | null;
            /** Devices Tested */
            devices_tested: string[];
            /** Display Name */
            display_name: string;
            /** Evidence */
            evidence?: string | null;
            /** Execution Semantics */
            execution_semantics: string;
            /** Export Formats */
            export_formats: string[];
            /** Family */
            family: string;
            /** Key */
            key: string;
            /** Legacy Backbone */
            legacy_backbone: string;
            /** Lookahead Note */
            lookahead_note: string;
            /** Lookahead Samples */
            lookahead_samples?: number | null;
            /** Params */
            params: components["schemas"]["ParamSpecInfo"][];
            /** Reference */
            reference?: string | null;
            /** Roles */
            roles: string[];
            /** Status */
            status: string;
            /** Training Method */
            training_method: string;
        };
        /** ModelSpec */
        ModelSpec: {
            /** Key */
            key: string;
            /** Parameters */
            parameters?: {
                [key: string]: number | string | boolean;
            };
        };
        /**
         * PAReference
         * @description The frozen PA surrogate a DPD task trains or evaluates through.
         */
        PAReference: {
            /** Checkpoint Artifact Id */
            checkpoint_artifact_id?: string | null;
            /** Checkpoint Sha256 */
            checkpoint_sha256?: string | null;
            model?: components["schemas"]["ModelSpec"] | null;
            /** Run Id */
            run_id: string;
        };
        /** ParamSpecInfo */
        ParamSpecInfo: {
            /** Choices */
            choices?: unknown[] | null;
            /** Default */
            default: unknown;
            /** Description */
            description: string;
            /** Legacy Arg */
            legacy_arg?: {
                [key: string]: string;
            };
            /** Maximum */
            maximum?: number | null;
            /** Minimum */
            minimum?: number | null;
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /** PreprocessPreview */
        PreprocessPreview: {
            /** N Samples After */
            n_samples_after: number;
            /** N Samples Before */
            n_samples_before: number;
            /** Record */
            record: {
                [key: string]: unknown;
            };
            report_after: components["schemas"]["DiagnosticReport"];
        };
        /** PreprocessRequest */
        PreprocessRequest: {
            /**
             * Base Version
             * @default raw-v1
             */
            base_version: string;
            params: components["schemas"]["PreprocessingParams"];
            /** Version */
            version?: string | null;
        };
        /**
         * PreprocessingParams
         * @description User-confirmed preprocessing; applied by ``opendpd.core.preprocess``.
         */
        PreprocessingParams: {
            /**
             * Delay Samples
             * @default 0
             */
            delay_samples: number;
            /**
             * Gain Db
             * @default 0
             */
            gain_db: number;
            /**
             * Interpolate Non Finite
             * @default false
             */
            interpolate_non_finite: boolean;
            /**
             * Normalize
             * @default none
             * @enum {string}
             */
            normalize: "none" | "peak_input";
            /**
             * Phase Deg
             * @default 0
             */
            phase_deg: number;
            /**
             * Remove Outliers
             * @default false
             */
            remove_outliers: boolean;
        };
        /** QuantizationConfig */
        QuantizationConfig: {
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * N Bits A
             * @default 8
             */
            n_bits_a: number;
            /**
             * N Bits W
             * @default 8
             */
            n_bits_w: number;
            /** Pretrained Run Id */
            pretrained_run_id?: string | null;
        };
        /** RecipeInfo */
        RecipeInfo: {
            /** Description */
            description: string;
            /** Expected Duration */
            expected_duration: string;
            /** Limits */
            limits: string;
            model: components["schemas"]["ModelSpec"];
            /** Purpose */
            purpose: string;
            /** Recipe Id */
            recipe_id: string;
            task: components["schemas"]["TaskType"];
            /** Title */
            title: string;
            training: components["schemas"]["TrainingConfig"];
        };
        /** ResolutionInfo */
        ResolutionInfo: {
            /** Config Sha256 */
            config_sha256: string;
            /** Defaults Source */
            defaults_source: string;
            /**
             * Resolved At
             * Format: date-time
             */
            resolved_at?: string;
            /** Resolver Version */
            resolver_version: string;
            /** Warnings */
            warnings?: string[];
        };
        /**
         * ResolvedExperimentConfig
         * @description Same shape as ``ExperimentConfig`` but every result-affecting default is
         *     explicit, model parameters are complete, and the checkpoint selection
         *     metric is set. Produced only by ``opendpd.services.config.resolve``.
         */
        ResolvedExperimentConfig: {
            dataset: components["schemas"]["DatasetRef"];
            dpd_reference?: components["schemas"]["DPDReference"] | null;
            evaluation?: components["schemas"]["EvaluationConfig"];
            execution?: components["schemas"]["ExecutionConfig"];
            model: components["schemas"]["ModelSpec"];
            /** Name */
            name?: string | null;
            /** Notes */
            notes?: string | null;
            pa_reference?: components["schemas"]["PAReference"] | null;
            quantization?: components["schemas"]["QuantizationConfig"] | null;
            /** Recipe Id */
            recipe_id?: string | null;
            resolution: components["schemas"]["ResolutionInfo"];
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            task: components["schemas"]["TaskType"];
            training?: components["schemas"]["TrainingConfig"];
        };
        /** RunError */
        RunError: {
            /** Code */
            code: string;
            /** Hint */
            hint?: string | null;
            /** Message */
            message: string;
            /** Stage */
            stage?: string | null;
            /** Traceback Tail */
            traceback_tail?: string | null;
        };
        /**
         * RunEvent
         * @description Append-only, strictly increasing ``seq`` per run. Clients resume from
         *     the last ``seq`` they saw; when the server can no longer replay from that
         *     point it answers with a snapshot requirement instead of guessing.
         */
        RunEvent: {
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            type: components["schemas"]["RunEventType"];
        };
        /**
         * RunEventType
         * @enum {string}
         */
        RunEventType: "status" | "progress" | "metric" | "log" | "artifact" | "checkpoint" | "heartbeat" | "error";
        /**
         * RunLineage
         * @description The experiment graph around one run: what it used (parents) and what used it (children).
         */
        RunLineage: {
            /** Children */
            children?: components["schemas"]["LineageLink"][];
            /** Parents */
            parents?: components["schemas"]["LineageLink"][];
            /** Run Id */
            run_id: string;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "succeeded" | "failed" | "cancel_requested" | "cancelled" | "interrupted";
        /** RunView */
        RunView: {
            /** Config Sha256 */
            config_sha256?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dataset Id */
            dataset_id?: string | null;
            /** Device */
            device?: string | null;
            error?: components["schemas"]["RunError"] | null;
            /** Exit Code */
            exit_code?: number | null;
            /** Experiment Id */
            experiment_id?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Heartbeat Stale
             * @default false
             */
            heartbeat_stale: boolean;
            /** Idempotency Key */
            idempotency_key?: string | null;
            /**
             * Last Event Seq
             * @default 0
             */
            last_event_seq: number;
            /** Last Heartbeat At */
            last_heartbeat_at?: string | null;
            /** Model Key */
            model_key?: string | null;
            /** Name */
            name?: string | null;
            /** Parent Run Id */
            parent_run_id?: string | null;
            /** Progress Epoch */
            progress_epoch?: number | null;
            /** Progress Total Epochs */
            progress_total_epochs?: number | null;
            /** Result Id */
            result_id?: string | null;
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["RunStatus"];
            /** Status Reason */
            status_reason?: string | null;
            task: components["schemas"]["TaskType"];
            worker?: components["schemas"]["WorkerInfo"] | null;
        };
        /**
         * ScalingInfo
         * @description What the amplitudes are relative to. Without a physical calibration no
         *     absolute power (dBm) or efficiency is derived from them.
         */
        ScalingInfo: {
            /**
             * Amplitude Units
             * @enum {string}
             */
            amplitude_units: "normalized" | "volts" | "unknown";
            /** Input Scaling */
            input_scaling: string;
            /**
             * Physical Calibration
             * @default false
             */
            physical_calibration: boolean;
            /** Reference Gain */
            reference_gain?: number | null;
        };
        /** SessionInfo */
        SessionInfo: {
            /** Authenticated */
            authenticated: boolean;
            /** Csrf Token */
            csrf_token?: string | null;
            /**
             * Version
             * @default 2.2.0.dev0
             */
            version: string;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "error" | "warning" | "info";
        /**
         * SignalReference
         * @description What the evaluated signal was compared against.
         */
        SignalReference: {
            /** Description */
            description: string;
            /** Gain Rule */
            gain_rule?: string | null;
            /** Gain Value */
            gain_value?: number | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "linear_gain_target" | "measured_pa_output" | "pa_surrogate_output";
        };
        /**
         * SignalSpec
         * @description Signal metadata needed by evaluation profiles. Unknown values stay
         *     ``None``; they are never guessed. ``missing_for_legacy_evaluation`` names
         *     what the legacy profile still needs.
         */
        SignalSpec: {
            /**
             * Amplitude Units
             * @default unknown
             * @enum {string}
             */
            amplitude_units: "normalized" | "volts" | "unknown";
            /** Bandwidth Hz */
            bandwidth_hz?: number | null;
            /** Modulation */
            modulation?: string | null;
            /** N Sub Ch */
            n_sub_ch?: number | null;
            /** Nperseg */
            nperseg?: number | null;
            /** Sample Rate Hz */
            sample_rate_hz?: number | null;
            /** Standard */
            standard?: string | null;
            /** Sub Channel Bandwidth Hz */
            sub_channel_bandwidth_hz?: number | null;
        };
        /**
         * SignalStage
         * @description One link of the evaluated signal chain: ``x`` (target input), ``u = DPD(x)``
         *     (pre-distorted PA input) and ``y`` (PA output). ``simulated`` is True when a
         *     learned surrogate produced the signal; it is never inferred from the task.
         */
        SignalStage: {
            /** Artifact Id */
            artifact_id?: string | null;
            /** N Samples */
            n_samples?: number | null;
            /** Peak Abs */
            peak_abs?: number | null;
            /** Rms */
            rms?: number | null;
            /** Role */
            role: string;
            /**
             * Simulated
             * @default false
             */
            simulated: boolean;
            /** Source */
            source: string;
            /**
             * Symbol
             * @enum {string}
             */
            symbol: "x" | "u" | "y";
        };
        /** SoftwareProvenance */
        SoftwareProvenance: {
            /** Git Commit */
            git_commit?: string | null;
            /** Git Dirty */
            git_dirty?: boolean | null;
            /** Opendpd Version */
            opendpd_version: string;
            /** Platform */
            platform: string;
            /** Python Version */
            python_version: string;
            /** Torch Version */
            torch_version?: string | null;
        };
        /** SourceInfoOut */
        SourceInfoOut: {
            /** Arrays */
            arrays: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Columns */
            columns: string[];
            /** Kind */
            kind: string;
            /** Legacy Files */
            legacy_files: string[];
            /** N Rows */
            n_rows?: number | null;
            /** Path */
            path: string;
            /** Preview */
            preview: {
                [key: string]: number;
            }[];
            /** Problems */
            problems: string[];
            /** Suggested Mapping */
            suggested_mapping: {
                [key: string]: string;
            };
        };
        /**
         * SourceRef
         * @description A file inside an authorised import root; clients never send absolute paths.
         */
        SourceRef: {
            /** Path */
            path: string;
            /** Root Id */
            root_id: string;
        };
        /**
         * SplitSpec
         * @description Contiguous train/val/test split performed *before* framing, with an
         *     optional guard band so overlapping frames never straddle a boundary.
         */
        SplitSpec: {
            /** Boundaries */
            boundaries?: {
                [key: string]: [
                    number,
                    number
                ];
            } | null;
            /**
             * Guard Samples
             * @default 0
             */
            guard_samples: number;
            /**
             * Method
             * @default contiguous
             * @constant
             */
            method: "contiguous";
            /** Ratios */
            ratios: {
                [key: string]: number;
            };
            /**
             * Version
             * @default contiguous-v1
             */
            version: string;
        };
        /** SubmitRunRequest */
        SubmitRunRequest: {
            config: components["schemas"]["ExperimentConfig"];
            /** Idempotency Key */
            idempotency_key?: string | null;
            /** Name */
            name?: string | null;
        };
        /**
         * SurrogateCoverage
         * @description How far the pre-distorted signal leaves the amplitude range the PA
         *     surrogate was fitted on. Evidence for an extrapolation warning only: staying
         *     inside the range does not prove the surrogate valid.
         */
        SurrogateCoverage: {
            /** Fitted Peak Abs */
            fitted_peak_abs: number;
            /** Fraction Above Fitted Peak */
            fraction_above_fitted_peak: number;
            /** Note */
            note: string;
            /** U Peak Abs */
            u_peak_abs: number;
        };
        /**
         * TaskType
         * @enum {string}
         */
        TaskType: "train_pa" | "train_dpd" | "run_dpd";
        /**
         * TrainingConfig
         * @description Defaults mirror the OpenDPDv2 recipe (arguments.py); they are the
         *     single source of defaults for every entry point.
         */
        TrainingConfig: {
            /**
             * Batch Size
             * @default 64
             */
            batch_size: number;
            /**
             * Batch Size Eval
             * @default 64
             */
            batch_size_eval: number;
            /**
             * Decay Factor
             * @default 0.5
             */
            decay_factor: number;
            /**
             * Epochs
             * @default 300
             */
            epochs: number;
            /**
             * Eval Test
             * @default true
             */
            eval_test: boolean;
            /**
             * Eval Val
             * @default true
             */
            eval_val: boolean;
            /**
             * Frame Length
             * @default 200
             */
            frame_length: number;
            /**
             * Frame Stride
             * @default 1
             */
            frame_stride: number;
            /**
             * Grad Clip
             * @default 200
             */
            grad_clip: number;
            /**
             * Learning Rate
             * @default 0.005
             */
            learning_rate: number;
            /**
             * Loss
             * @default l2
             * @enum {string}
             */
            loss: "l2" | "l1";
            /**
             * Lr End
             * @default 0.00005
             */
            lr_end: number;
            /**
             * Lr Schedule
             * @default true
             */
            lr_schedule: boolean;
            /**
             * Optimizer
             * @default adamw
             * @enum {string}
             */
            optimizer: "adamw" | "adam" | "sgd" | "rmsprop";
            /**
             * Patience
             * @default 5
             */
            patience: number;
            /**
             * Reproducibility
             * @default soft
             * @enum {string}
             */
            reproducibility: "soft" | "hard";
            /**
             * Seed
             * @default 0
             */
            seed: number;
        };
        /** UploadResult */
        UploadResult: {
            /** Path */
            path: string;
            /** Root Id */
            root_id: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /** ValidateRequest */
        ValidateRequest: {
            /** Config */
            config: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkerInfo
         * @description Identity of the worker process. PID alone is never trusted: the
         *     process creation time must match too (PIDs are recycled).
         */
        WorkerInfo: {
            /** Create Time */
            create_time: number;
            /** Host */
            host: string;
            /** Pid */
            pid: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    artifact_download_api_v1_artifacts__run_id___artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    datasets_list_api_v1_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetManifest"][];
                };
            };
        };
    };
    dataset_import_api_v1_datasets_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetManifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_import_builtin_api_v1_datasets_import_builtin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportBuiltinRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetManifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_roots_api_v1_datasets_import_roots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportRootInfo"][];
                };
            };
        };
    };
    import_root_files_api_v1_datasets_import_roots__root_id__files_get: {
        parameters: {
            query?: {
                path?: string;
            };
            header?: never;
            path: {
                root_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileEntryInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_inspect_api_v1_datasets_inspect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceRef"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceInfoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_upload_api_v1_datasets_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_dataset_upload_api_v1_datasets_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_get_api_v1_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetManifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_diagnostics_latest_api_v1_datasets__dataset_id__diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticReport"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_diagnostics_run_api_v1_datasets__dataset_id__diagnostics_post: {
        parameters: {
            query?: {
                version?: string;
            };
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_update_api_v1_datasets__dataset_id__manifest_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManifestUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetManifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_preprocess_api_v1_datasets__dataset_id__preprocess_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreprocessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetVersion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_preprocess_preview_api_v1_datasets__dataset_id__preprocess_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreprocessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreprocessPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    experiments_validate_api_v1_experiments_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metric_profiles_api_v1_metrics_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricProfile"][];
                };
            };
        };
    };
    metric_profile_api_v1_metrics_profiles__profile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfo"][];
                };
            };
        };
    };
    recipes_api_v1_recipes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeInfo"][];
                };
            };
        };
    };
    results_compare_api_v1_results_compare_get: {
        parameters: {
            query: {
                runs: string[];
                profile?: string | null;
                format?: "json" | "csv";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    results_get_api_v1_results__run_id__get: {
        parameters: {
            query?: {
                profile?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    results_profiles_api_v1_results__run_id__profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_list_api_v1_runs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["RunStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_submit_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_get_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_artifacts_api_v1_runs__run_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactManifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_cancel_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_config_api_v1_runs__run_id__config_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedExperimentConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_stream_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_list_api_v1_runs__run_id__events_list_get: {
        parameters: {
            query?: {
                after?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_history_api_v1_runs__run_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_lineage_api_v1_runs__run_id__lineage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunLineage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_logs_api_v1_runs__run_id__logs_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_retry_api_v1_runs__run_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_info_api_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
        };
    };
    session_bootstrap_api_v1_session_bootstrap_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BootstrapRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_api_v1_system_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
}
