"""Lazy constructors shared by the compatibility CLI and model registry."""
from importlib import import_module

# Parameter names reference CoreModel's explicit construction context.
BACKBONE_BUILDERS = {'gmp': ('backbones.gmp', 'GMP', {}),
 'gru': ('backbones.gru',
         'GRU',
         {'input_size': 'input_size',
          'hidden_size': 'hidden_size',
          'output_size': 'output_size',
          'num_layers': 'num_layers',
          'bidirectional': 'bidirectional',
          'batch_first': 'batch_first',
          'bias': 'bias'}),
 'dgru': ('backbones.dgru',
          'DGRU',
          {'hidden_size': 'hidden_size',
           'output_size': 'output_size',
           'num_layers': 'num_layers',
           'bidirectional': 'bidirectional',
           'batch_first': 'batch_first',
           'bias': 'bias'}),
 'qgru': ('backbones.qgru',
          'QGRU',
          {'hidden_size': 'hidden_size',
           'output_size': 'output_size',
           'num_layers': 'num_layers',
           'bidirectional': 'bidirectional',
           'batch_first': 'batch_first',
           'bias': 'bias'}),
 'qgru_amp1': ('backbones.qgru_amp1',
               'QGRU',
               {'hidden_size': 'hidden_size',
                'output_size': 'output_size',
                'num_layers': 'num_layers',
                'bidirectional': 'bidirectional',
                'batch_first': 'batch_first',
                'bias': 'bias'}),
 'lstm': ('backbones.lstm',
          'LSTM',
          {'input_size': 'input_size',
           'hidden_size': 'hidden_size',
           'output_size': 'output_size',
           'num_layers': 'num_layers',
           'bidirectional': 'bidirectional',
           'batch_first': 'batch_first',
           'bias': 'bias'}),
 'vdlstm': ('backbones.vdlstm',
            'VDLSTM',
            {'input_size': 'input_size',
             'hidden_size': 'hidden_size',
             'output_size': 'output_size',
             'num_layers': 'num_layers',
             'bidirectional': 'bidirectional',
             'batch_first': 'batch_first',
             'bias': 'bias'}),
 'rvtdcnn': ('backbones.rvtdcnn', 'RVTDCNN', {'fc_hid_size': 'hidden_size'}),
 'apnrru': ('backbones.apnrru', 'APNRRU', {'hidden_size': 'hidden_size', 'bias': 'bias'}),
 'bojanet': ('backbones.bojanet',
             'BOJANET',
             {'hidden_size': 'hidden_size', 'output_size': 'output_size', 'bias': 'bias'}),
 'deltagru': ('backbones.deltagru',
              'DeltaGRU',
              {'input_size': '6',
               'hidden_size': 'hidden_size',
               'output_size': 'output_size',
               'num_layers': 'num_layers',
               'thx': 'thx',
               'thh': 'thh',
               'bias': 'bias'}),
 'deltajanet': ('backbones.deltajanet',
                'DeltaJANET',
                {'input_size': '6',
                 'hidden_size': 'hidden_size',
                 'output_size': 'output_size',
                 'num_layers': 'num_layers',
                 'thx': 'thx',
                 'thh': 'thh',
                 'bias': 'bias'}),
 'pgjanet': ('backbones.pgjanet',
             'PGJANET',
             {'hidden_size': 'hidden_size', 'output_size': 'output_size', 'bias': 'bias'}),
 'dvrjanet': ('backbones.dvrjanet',
              'DVRJANET',
              {'hidden_size': 'hidden_size',
               'output_size': 'output_size',
               'num_dvr_units': 'num_dvr_units',
               'bias': 'bias'}),
 'tres_deltagru': ('backbones.tres_deltagru',
                   'TResDeltaGRU',
                   {'input_size': '6',
                    'hidden_size': 'hidden_size',
                    'output_size': 'output_size',
                    'num_layers': 'num_layers',
                    'thx': 'thx',
                    'thh': 'thh',
                    'bias': 'bias'}),
 'tres_gru': ('backbones.tres_gru',
              'TResGRU',
              {'input_size': '6',
               'hidden_size': 'hidden_size',
               'output_size': 'output_size',
               'num_layers': 'num_layers',
               'bias': 'bias'}),
 'tcn': ('backbones.tcn', 'TCN', {'hidden_channels': 'hidden_size'}),
 'mcldnn': ('backbones.mcldnn', 'MCLDNN', {'hidden_size': 'hidden_size'})}


def build_backbone(name, context):
    try:
        module, symbol, fields = BACKBONE_BUILDERS[name]
    except KeyError:
        raise ValueError(f'Unsupported backbone: {name}') from None
    params = {key: int(value) if value.isdigit() else context[value] for key, value in fields.items()}
    return getattr(import_module(module), symbol)(**params)
