function mark = codegenMark()
%CODEGENMARK The sentence that every file written by opendpd.generateCode contains.
% opendpd.generateCode replaces an existing file only if it contains this sentence, so a file of the user's own is never
% overwritten, and the format name in it changes whenever the generated code changes in a way that matters to its users.
mark = "Generated by opendpd.generateCode (opendpd-codegen-v1)";
end
