function results = parityMP(inputFile, outputFile)
%PARITYMP MATLAB side of the memory-polynomial DPD parity registered in docs/performance/matlab-parity-dpd.md.
%   RESULTS = parityMP(INPUTFILE, OUTPUTFILE) reads the data written by scripts/matlab_parity_dpd.py (a MAT file
%   with the arrays and a JSON file with the case list) and, with comm.DPDCoefficientEstimator and comm.DPD only,
%   computes for every case
%     Q1      the coefficients estimated from the constructed exact problem,
%     Q3      the constructed input regenerated by comm.DPD from the true coefficients,
%     D1, Q4  the coefficients estimated from the plant data, and the predistorter output they give,
%     Q5      the output of comm.DPD with the coefficients OpenDPD estimated, for float32-rounded input,
%     D3      the coefficients when DesiredAmplitudeGaindB is read as 20*log10(G),
%   and, for the product-path run, the coefficients estimated from the run's stored train split (D4).
%   The arrays go to the MAT file next to OUTPUTFILE; the environment and timings go to OUTPUTFILE as JSON.
%   Nothing here calls OpenDPD and nothing is judged: the comparison and the budgets are applied by
%   scripts/matlab_parity_dpd.py.
%
%   Requires Communications Toolbox.
arguments
    inputFile (1,1) string {mustBeFile}
    outputFile (1,1) string
end
description = jsondecode(fileread(replace(inputFile, ".mat", ".json")));
data = load(inputFile);

arrays = struct();
timing = struct();
settings = struct();
for c = description.cases(:).'
    id = string(c.id);
    x = data.("x_" + c.record);
    y = data.("y_" + c.record);
    x = x(:);
    y = y(:);
    K = c.degree;
    Q = c.memory_depth;
    gainDb = 10 * log10(c.gain);                          % registered: equal divisors, 10^(g/10) == G
    started = tic;

    arrays.(id + "_coef_exact") = estimate(data.("xsyn_" + id)(:), y, K, Q, gainDb);                 % Q1
    arrays.(id + "_u_true") = predistort(reshape(data.("ctrue_" + id)(:), Q, K), y / c.gain);         % Q3
    coef = estimate(x, y, K, Q, gainDb);                                                             % D1
    arrays.(id + "_coef") = coef;
    arrays.(id + "_u_own") = predistort(coef, x);                                                    % Q4
    arrays.(id + "_u_od") = predistort(reshape(data.("wod_" + id)(:), Q, K), double(single(x)));      % Q5
    arrays.(id + "_coef_gain20") = estimate(x, y, K, Q, 20 * log10(c.gain));                         % D3

    timing.(id) = toc(started);
    settings.(id) = struct('degree', K, 'memory_depth', Q, 'gain', c.gain, 'desired_amplitude_gain_db', gainDb);
end

if isfield(description, 'product_path')                                                              % D4
    p = description.product_path;
    arrays.pp_coef = estimate(double(data.pp_x(:)), double(data.pp_y(:)), p.degree, p.memory_depth, 10 * log10(p.gain));
    settings.pp = struct('degree', p.degree, 'memory_depth', p.memory_depth, 'gain', p.gain, ...
        'desired_amplitude_gain_db', 10 * log10(p.gain));
end

matFile = replace(outputFile, ".json", ".mat");
save(matFile, '-struct', 'arrays', '-v7');

results = struct('environment', environment(), 'timing_seconds', timing, 'settings', settings, 'arrays_file', matFile);
fid = fopen(outputFile, 'w');
cleanup = onCleanup(@() fclose(fid));
fwrite(fid, jsonencode(results, PrettyPrint=true), 'char');
end

function coef = estimate(paInput, paOutput, degree, memoryDepth, gainDb)
% The registered MathWorks configuration; PA_input is the signal the fitted postdistorter should return.
estimator = comm.DPDCoefficientEstimator('PolynomialType', 'Memory polynomial', 'Algorithm', 'Least squares', ...
    'Degree', degree, 'MemoryDepth', memoryDepth, 'DesiredAmplitudeGaindB', gainDb);
coef = estimator(paInput, paOutput);
end

function u = predistort(coef, v)
dpd = comm.DPD('PolynomialType', 'Memory polynomial', 'Coefficients', coef);
u = dpd(v);
end

function e = environment()
products = ver;
e = struct('matlab', version, 'release', version('-release'));
for name = ["Communications Toolbox"]
    index = find(strcmp({products.Name}, name), 1);
    key = strrep(char(name), ' ', '_');
    if isempty(index)
        e.(key) = 'not installed';
    else
        e.(key) = products(index).Version;
    end
end
end
