"""Reconcile tested Dependabot PRs, or fail a release with actionable pending PRs.

Run only from trusted main with a short-lived GitHub Actions token. PR files are
read as data. No PR checkout, package installation, secrets, or PR-supplied shell.
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import sys
import time
import urllib.error

sys.path.insert(0, str(Path(__file__).resolve().parent))
from dependency_github import GitHub
from dependency_policy import dependabot_pr

WORKFLOWS = {
    "ci.yml": {"Lint (critical errors)", "Build & check distribution", "Release dependency readiness",
               "Frontend (types, lint, unit, build, browser journeys)",
               *{f"Tests (Python {v})" for v in ("3.10", "3.11", "3.12", "3.13")},
               *{f"Default install ({os})" for os in ("ubuntu-latest", "macos-latest", "windows-latest")}},
    "docs.yml": {"Build site"},
    "dependency-audit.yml": {"audit"},
}


def dependency_pr(pr):
    return (pr.get("user", {}).get("login") == "dependabot[bot]"
            or any(label.get("name") == "dependencies" for label in pr.get("labels", [])))


def latest_run(api, workflow, sha):
    data = api.request(f"actions/workflows/{workflow}/runs?head_sha={sha}&per_page=100")
    if data.get("total_count", 0) > 100:
        raise ValueError("too many workflow runs to audit")
    runs = [run for run in data["workflow_runs"] if run["head_sha"] == sha
            and run["event"] in {"pull_request", "workflow_dispatch", "push"}
            and run.get("head_repository", {}).get("full_name") == api.repository]
    # GitHub may require manual approval for PR events generated by GITHUB_TOKEN.
    # We explicitly dispatch the same read-only checks; an unstarted PR event is
    # not a test result. Real failed runs are never filtered out.
    if any(run["event"] == "workflow_dispatch" for run in runs):
        runs = [run for run in runs if run.get("conclusion") != "action_required" and run["status"] != "waiting"]
    return max(runs, key=lambda run: run["id"]) if runs else None


def validation(api, sha, ref=None):
    waiting = False
    for workflow, required in WORKFLOWS.items():
        run = latest_run(api, workflow, sha)
        if not run:
            if ref is not None:
                api.request(f"actions/workflows/{workflow}/dispatches", {"ref": ref})
            waiting = True
            continue
        if run["status"] != "completed":
            waiting = True
            continue
        if run["conclusion"] != "success":
            return "failed", run["html_url"]
        jobs = api.request(f"actions/runs/{run['id']}/jobs?filter=latest&per_page=100")
        if jobs.get("total_count", 0) > 100:
            raise ValueError("incomplete workflow job list")
        passed = {job["name"] for job in jobs["jobs"]
                  if job["status"] == "completed" and job["conclusion"] == "success"}
        if not required <= passed:
            return "failed", f"{run['html_url']} (required jobs missing or skipped)"
    return ("waiting", "checks are running or newly dispatched") if waiting else ("passed", "all required checks passed")


def require_strict_checks(api):
    """GitHub must enforce the base-SHA race boundary at the merge operation."""
    required = set().union(*WORKFLOWS.values())
    # This endpoint needs only metadata read access. The classic protection
    # endpoint needs administration access, which GITHUB_TOKEN must not hold.
    for rule in api.pages("rules/branches/main"):
        if rule["type"] != "required_status_checks":
            continue
        checks = rule.get("parameters") or {}
        names = {item["context"] for item in checks.get("required_status_checks", [])
                 if item.get("integration_id") == 15368}  # GitHub Actions
        if checks.get("strict_required_status_checks_policy") and required <= names:
            return
    raise ValueError("main must require up-to-date branches and the documented GitHub Actions checks in an active ruleset")


def reconcile(api):
    require_strict_checks(api)
    report = []
    for item in sorted(api.pulls(), key=lambda pr: pr["number"]):
        if not dependency_pr(item):
            continue
        number = item["number"]
        pr = api.request(f"pulls/{number}")
        if pr["state"] != "open":
            continue
        if dependabot_pr(pr) and not api.files(pr):
            api.request(f"pulls/{number}", {"state": "closed"}, method="PATCH")
            report.append(f"#{number}: closed empty update already included in main")
            continue
        if not dependabot_pr(pr) or not api.routine(pr):
            report.append(f"#{number}: human review required (major/core dependency or non-routine diff)")
            continue
        if api.comparison(pr)["behind_by"]:
            # Keep updates small and validate them together with the current main.
            old = pr["head"]["sha"]
            api.request(f"pulls/{number}/update-branch", {"expected_head_sha": old}, method="PUT")
            for _ in range(15):
                time.sleep(2)
                pr = api.request(f"pulls/{number}")
                if pr["head"]["sha"] != old:
                    break
            else:
                report.append(f"#{number}: branch update is pending")
                continue
            if not api.files(pr):
                api.request(f"pulls/{number}", {"state": "closed"}, method="PATCH")
                report.append(f"#{number}: closed update already included in main after refresh")
                continue
            if not api.routine(pr) or api.comparison(pr)["behind_by"]:
                report.append(f"#{number}: branch changed; waiting for a fresh review")
                continue
        sha = pr["head"]["sha"]
        state, detail = validation(api, sha, pr["head"]["ref"])
        if state != "passed":
            report.append(f"#{number}: {state}: {detail}")
            continue
        require_strict_checks(api)
        fresh = api.request(f"pulls/{number}")
        if fresh["state"] != "open" or fresh["head"]["sha"] != sha or api.comparison(fresh)["behind_by"]:
            report.append(f"#{number}: source changed during checks; retry later")
            continue
        result = api.request(f"pulls/{number}/merge", {"sha": sha, "merge_method": "squash"}, method="PUT")
        if not result.get("merged"):
            raise ValueError(f"#{number}: GitHub refused the merge")
        report.append(f"#{number}: merged {result['sha']}")
        # Token-created pushes do not automatically run push workflows.
        for workflow in WORKFLOWS:
            api.request(f"actions/workflows/{workflow}/dispatches", {"ref": "main"})
        # Re-read all PR/base identities in the next serialized invocation.
        break
    return report


def release_check(api, release_sha=None, exclude_pr=None):
    pending = [pr["number"] for pr in api.pulls() if dependency_pr(pr) and pr["number"] != exclude_pr]
    if pending:
        raise ValueError("Unresolved dependency PRs: " + ", ".join(f"#{n}" for n in pending)
                         + ". Run Dependency maintenance; resolve failed/major updates before creating the release.")
    if release_sha:
        if not re.fullmatch(r"[a-f0-9]{40}", release_sha):
            raise ValueError("release must identify an immutable commit")
        # The tag must include the maintenance commits, not just coexist with them.
        main = api.request("git/ref/heads/main")["object"]["sha"]
        release_tree = api.request(f"git/commits/{release_sha}")["tree"]["sha"]
        main_tree = api.request(f"git/commits/{main}")["tree"]["sha"]
        if release_tree != main_tree:
            raise ValueError("Release source differs from current main; prepare and test a fresh release after dependency maintenance.")
        state, detail = validation(api, release_sha)
        if state == "waiting":
            # A squash merge has a new commit ID but the exact tested PR tree.
            # Never override an actual failure on the release commit.
            for pr in api.pages(f"commits/{release_sha}/pulls"):
                if (not pr.get("merged_at") or pr["base"]["ref"] != "main"
                        or pr["head"]["repo"]["full_name"] != api.repository):
                    continue
                head = pr["head"]["sha"]
                if api.request(f"git/commits/{head}")["tree"]["sha"] == release_tree:
                    state, detail = validation(api, head)
                    if state == "passed":
                        break
        if state != "passed":
            raise ValueError(f"Release CI is {state}: {detail}")
    return "No unresolved dependency PRs; release source and checks are current."


def version_change_check(api, event, event_name, sha):
    """Block a version promotion before merging, while allowing dependency PRs to clear the queue."""
    pull = event.get("pull_request")
    if pull:
        before, after, exclude = pull["base"]["sha"], pull["head"]["sha"], pull["number"]
    elif event_name == "push":
        before, after, exclude = event["before"], event["after"], None
    else:
        before = api.request("git/ref/heads/main")["object"]["sha"]
        after, exclude = sha, None
    if before == after:
        return "No version promotion in this dispatch."
    patterns = {
        "opendpd/__init__.py": r'^__version__ = "([^"]+)"',
        "pyproject.toml": r'^version = "([^"]+)"',
    }
    def versions(ref):
        values = []
        for path, pattern in patterns.items():
            match = re.search(pattern, api.source(ref, path), re.M)
            if not match:
                raise ValueError("Cannot determine package version")
            values.append(match[1])
        values.append(json.loads(api.source(ref, "frontend/package.json"))["version"])
        return values
    if versions(before) == versions(after):
        return "Package versions are unchanged; dependency maintenance may proceed."
    release_check(api, exclude_pr=exclude)
    return "Version promotion has no unresolved dependency PRs."


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="read-only release gate")
    mode.add_argument("--version-change", action="store_true", help="read-only gate before merging a version PR")
    parser.add_argument("--sha", help="release commit (required for publication)")
    parser.add_argument("--wait", type=int, default=0, choices=range(0, 121), metavar="MINUTES",
                        help="finish routine updates before a release; at most 120 minutes")
    args = parser.parse_args(argv)
    api = GitHub()
    output = []
    try:
        if args.version_change:
            event = json.loads(Path(os.environ["GITHUB_EVENT_PATH"]).read_text())
            output.append(version_change_check(api, event, os.environ["GITHUB_EVENT_NAME"], os.environ["GITHUB_SHA"]))
        elif args.check:
            output.append(release_check(api, args.sha))
        else:
            deadline = time.monotonic() + args.wait * 60
            while True:
                output = reconcile(api)
                pending = [pr for pr in api.pulls() if dependency_pr(pr)]
                if not pending:
                    output.append("Dependency backlog is empty.")
                    break
                if not args.wait:
                    break
                if any("human review required" in line or ": failed:" in line for line in output):
                    raise ValueError("\n".join(output))
                if time.monotonic() >= deadline:
                    raise ValueError("Dependency checks are still pending; release is blocked.\n" + "\n".join(output))
                # Full CI takes minutes. Leave room within GITHUB_TOKEN's
                # repository rate limit while multiple ecosystems are pending.
                time.sleep(180)
    except (ValueError, KeyError, urllib.error.HTTPError, urllib.error.URLError) as error:
        output.append(f"Dependency maintenance did not authorize publication: {error}")
        code = 1
    else:
        code = 0
    for line in output:
        print(line)
    if os.environ.get("GITHUB_STEP_SUMMARY"):
        with open(os.environ["GITHUB_STEP_SUMMARY"], "a") as stream:
            stream.write("## Dependency maintenance\n\n" + "\n".join("- " + line for line in output) + "\n")
    return code


if __name__ == "__main__":
    raise SystemExit(main())
