"""C99 backend of ``fixed-point-v1``: the same integer steps as ``opendpd.core.fixed_point``, generated with the
quantised weights and tables baked in, plus a harness that replays golden vectors. ``verify`` compiles the sources
with the system C compiler and compares every output sample and every state step with the software reference,
so a mismatch is reported at a sample and a signal, never as a metric difference."""

from __future__ import annotations

import shutil
import subprocess
import time
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

from opendpd.core.fixed_point import FixedGRU, QuantisedGRU
from opendpd.schemas.fixed_point import Verification

BACKEND = "c99"
SOURCES = ("gru_fixed.h", "gru_fixed.c", "harness.c")


def _c_array(name: str, values: np.ndarray, ctype: str) -> str:
    flat = np.asarray(values, dtype=np.int64).ravel()
    dims = "".join(f"[{d}]" for d in values.shape)
    body = ",\n    ".join(", ".join(str(int(v)) for v in flat[i:i + 12]) for i in range(0, flat.size, 12))
    return f"static const {ctype} {name}{dims} = {{\n    {body}\n}};\n"


def generate(q: QuantisedGRU) -> Dict[str, str]:
    """Sources by file name: the fixed-point step (``gru_fixed.c/.h``) and the golden-vector harness."""
    s = q.spec
    header = f"""/* {s.spec_id}: bit-exact GRU reference generated by OpenDPD. Two's complement integers; every right shift
 * is a floor (implemented with division, so no arithmetic-shift assumption); every stored quantity saturates. */
#ifndef GRU_FIXED_H
#define GRU_FIXED_H
#include <stdint.h>
#define GRU_HIDDEN {q.hidden}
#define GRU_INPUTS {q.inputs}
#define GRU_OUTPUTS {q.outputs}
#define X_FRAC {s.x.frac}
#define H_FRAC {s.h.frac}
#define Y_FRAC {s.y.frac}
#define PRE_FRAC {s.pre.frac}
#define F_IH {q.f_ih}
#define F_HH {q.f_hh}
#define F_OUT {q.f_out}
#define SIG_RANGE {int(s.sigmoid.range * (1 << s.sigmoid.index_frac))}
#define SIG_IDX_FRAC {s.sigmoid.index_frac}
#define TANH_RANGE {int(s.tanh.range * (1 << s.tanh.index_frac))}
#define TANH_IDX_FRAC {s.tanh.index_frac}
typedef struct {{ int16_t h[GRU_HIDDEN]; }} gru_state_t;
void gru_fixed_reset(gru_state_t *st);
void gru_fixed_step(gru_state_t *st, const int16_t x[GRU_INPUTS], int16_t y[GRU_OUTPUTS]);
#endif
"""
    source = f"""#include "gru_fixed.h"
{_c_array("W_IH", q.w_ih, "int16_t")}{_c_array("W_HH", q.w_hh, "int16_t")}{_c_array("W_OUT", q.w_out, "int16_t")}
{_c_array("B_IH", q.b_ih, "int32_t")}{_c_array("B_HH", q.b_hh, "int32_t")}{_c_array("B_OUT", q.b_out, "int32_t")}
{_c_array("SIGMOID_LUT", q.sigmoid_table, "int16_t")}{_c_array("TANH_LUT", q.tanh_table, "int16_t")}
static int64_t floor_div_pow2(int64_t v, int s) {{
    int64_t d = (int64_t)1 << s;
    int64_t quot = v / d;
    if ((v % d) < 0) quot -= 1;
    return quot;
}}
static int64_t rescale(int64_t v, int from_frac, int to_frac) {{
    if (to_frac >= from_frac) return v << (to_frac - from_frac);
    int s = from_frac - to_frac;
    return floor_div_pow2(v + ((int64_t)1 << (s - 1)), s);
}}
static int64_t sat(int64_t v, int bits) {{
    int64_t hi = ((int64_t)1 << (bits - 1)) - 1, lo = -((int64_t)1 << (bits - 1));
    return v > hi ? hi : (v < lo ? lo : v);
}}
static int16_t lut(int64_t pre, const int16_t *tab, int range, int idx_frac) {{
    int64_t idx = rescale(pre, PRE_FRAC, idx_frac);
    if (idx < -range) idx = -range;
    if (idx > range - 1) idx = range - 1;
    return tab[idx + range];
}}
void gru_fixed_reset(gru_state_t *st) {{
    for (int i = 0; i < GRU_HIDDEN; i++) st->h[i] = 0;
}}
void gru_fixed_step(gru_state_t *st, const int16_t x[GRU_INPUTS], int16_t y[GRU_OUTPUTS]) {{
    int64_t ai[3 * GRU_HIDDEN], ah[3 * GRU_HIDDEN];
    int16_t r[GRU_HIDDEN], z[GRU_HIDDEN], n[GRU_HIDDEN], h_new[GRU_HIDDEN];
    for (int g = 0; g < 3 * GRU_HIDDEN; g++) {{
        int64_t acc_i = 0, acc_h = 0;
        for (int j = 0; j < GRU_INPUTS; j++) acc_i += (int64_t)W_IH[g][j] * (int64_t)x[j];
        for (int j = 0; j < GRU_HIDDEN; j++) acc_h += (int64_t)W_HH[g][j] * (int64_t)st->h[j];
        ai[g] = sat(rescale(acc_i, F_IH + X_FRAC, PRE_FRAC) + B_IH[g], {s.pre.bits});
        ah[g] = sat(rescale(acc_h, F_HH + H_FRAC, PRE_FRAC) + B_HH[g], {s.pre.bits});
    }}
    for (int i = 0; i < GRU_HIDDEN; i++) {{
        r[i] = lut(sat(ai[i] + ah[i], {s.pre.bits}), SIGMOID_LUT, SIG_RANGE, SIG_IDX_FRAC);
        z[i] = lut(sat(ai[GRU_HIDDEN + i] + ah[GRU_HIDDEN + i], {s.pre.bits}), SIGMOID_LUT, SIG_RANGE, SIG_IDX_FRAC);
        int64_t t = rescale((int64_t)r[i] * ah[2 * GRU_HIDDEN + i], H_FRAC + PRE_FRAC, PRE_FRAC);
        n[i] = lut(sat(ai[2 * GRU_HIDDEN + i] + t, {s.pre.bits}), TANH_LUT, TANH_RANGE, TANH_IDX_FRAC);
        int64_t one = (int64_t)1 << H_FRAC;
        int64_t mix = (one - (int64_t)z[i]) * (int64_t)n[i] + (int64_t)z[i] * (int64_t)st->h[i];
        h_new[i] = (int16_t)sat(rescale(mix, 2 * H_FRAC, H_FRAC), {s.h.bits});
    }}
    for (int k = 0; k < GRU_OUTPUTS; k++) {{
        int64_t acc = 0;
        for (int j = 0; j < GRU_HIDDEN; j++) acc += (int64_t)W_OUT[k][j] * (int64_t)h_new[j];
        int64_t pre = sat(rescale(acc, F_OUT + H_FRAC, PRE_FRAC) + B_OUT[k], {s.pre.bits});
        y[k] = (int16_t)sat(rescale(pre, PRE_FRAC, Y_FRAC), {s.y.bits});
    }}
    for (int i = 0; i < GRU_HIDDEN; i++) st->h[i] = h_new[i];
}}
"""
    harness = """/* Replays a golden vector: harness x.i16 n y.out h.out [reset_index ...]
 * x.i16: n * GRU_INPUTS little-endian int16; writes y (n * GRU_OUTPUTS) and the per-step state (n * GRU_HIDDEN). */
#include <stdio.h>
#include <stdlib.h>
#include "gru_fixed.h"
int main(int argc, char **argv) {
    if (argc < 5) { fprintf(stderr, "usage: harness x.i16 n y.out h.out [reset ...]\\n"); return 2; }
    long n = atol(argv[2]);
    FILE *fx = fopen(argv[1], "rb"), *fy = fopen(argv[3], "wb"), *fh = fopen(argv[4], "wb");
    if (!fx || !fy || !fh) { fprintf(stderr, "cannot open files\\n"); return 2; }
    int n_resets = argc - 5;
    long *resets = n_resets ? (long *)malloc(sizeof(long) * n_resets) : NULL;
    for (int i = 0; i < n_resets; i++) resets[i] = atol(argv[5 + i]);
    gru_state_t st;
    gru_fixed_reset(&st);
    int16_t x[GRU_INPUTS], y[GRU_OUTPUTS];
    for (long i = 0; i < n; i++) {
        for (int k = 0; k < n_resets; k++) if (resets[k] == i) gru_fixed_reset(&st);
        if (fread(x, sizeof(int16_t), GRU_INPUTS, fx) != (size_t)GRU_INPUTS) { fprintf(stderr, "short input\\n"); return 3; }
        gru_fixed_step(&st, x, y);
        fwrite(y, sizeof(int16_t), GRU_OUTPUTS, fy);
        fwrite(st.h, sizeof(int16_t), GRU_HIDDEN, fh);
    }
    fclose(fx); fclose(fy); fclose(fh);
    free(resets);
    return 0;
}
"""
    return {"gru_fixed.h": header, "gru_fixed.c": source, "harness.c": harness}


def compiler() -> Optional[str]:
    return shutil.which("cc") or shutil.which("gcc") or shutil.which("clang")


def build(src_dir: Path) -> Path:
    """Compile the generated sources into ``src_dir/harness``; raises RuntimeError with the compiler output."""
    cc = compiler()
    if cc is None:
        raise RuntimeError("no C compiler (cc, gcc or clang) on PATH")
    exe = src_dir / "harness"
    proc = subprocess.run([cc, "-std=c99", "-O2", "-o", str(exe), str(src_dir / "gru_fixed.c"), str(src_dir / "harness.c")],
                          capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(f"{cc} failed:\n{proc.stderr[-2000:]}")
    return exe


def run_case(exe: Path, x_q: np.ndarray, resets_at: Tuple[int, ...], work: Path, hidden: int) -> Tuple[np.ndarray, np.ndarray, float]:
    """Replay one vector through the compiled harness; returns (y, per-step h, seconds)."""
    work.mkdir(parents=True, exist_ok=True)
    x_path, y_path, h_path = work / "x.i16", work / "y.out", work / "h.out"
    x_path.write_bytes(np.asarray(x_q, dtype="<i2").tobytes())
    args = [str(exe), str(x_path), str(x_q.shape[0]), str(y_path), str(h_path)] + [str(i) for i in resets_at]
    t0 = time.perf_counter()
    proc = subprocess.run(args, capture_output=True, text=True)
    dt = time.perf_counter() - t0
    if proc.returncode != 0:
        raise RuntimeError(f"harness failed ({proc.returncode}): {proc.stderr[-500:]}")
    y = np.frombuffer(y_path.read_bytes(), dtype="<i2").astype(np.int64).reshape(x_q.shape[0], -1)
    h = np.frombuffer(h_path.read_bytes(), dtype="<i2").astype(np.int64).reshape(x_q.shape[0], hidden)
    return y, h, dt


def first_mismatch(ref_y: np.ndarray, ref_h: np.ndarray, got_y: np.ndarray, got_h: np.ndarray) -> Optional[Tuple[int, str]]:
    """The first (step, signal) where the target differs from the reference; the state is checked before the
    output of the same step because the output is computed from it."""
    n = min(ref_y.shape[0], got_y.shape[0])
    for i in range(n):
        if not np.array_equal(ref_h[i], got_h[i]):
            return i, "h"
        if not np.array_equal(ref_y[i], got_y[i]):
            return i, "y"
    if ref_y.shape[0] != got_y.shape[0]:
        return n, "length"
    return None


def verify(q: QuantisedGRU, cases: List[Tuple[str, np.ndarray, Tuple[int, ...]]], work: Path) -> Tuple[Verification, Dict[str, float]]:
    """Generate, compile and replay every case; the software reference is recomputed here, never trusted from a
    file. Returns the verification and the harness seconds per case."""
    work.mkdir(parents=True, exist_ok=True)
    for name, text in generate(q).items():
        (work / name).write_text(text, encoding="utf-8")
    cc = compiler()
    if cc is None:
        return Verification(backend=BACKEND, status="not_run", cases_checked=0,
                            detail="no C compiler (cc, gcc or clang) on PATH: the sources were generated but not verified"), {}
    try:
        exe = build(work)
    except RuntimeError as err:
        return Verification(backend=BACKEND, status="not_run", compiler=cc, cases_checked=0, detail=str(err)), {}
    seconds: Dict[str, float] = {}
    for i, (case_id, x_q, resets_at) in enumerate(cases):
        ref_y, traces = FixedGRU(q).run(x_q, resets_at, trace=True)
        got_y, got_h, seconds[case_id] = run_case(exe, x_q, resets_at, work / case_id, q.hidden)
        where = first_mismatch(ref_y, traces["h"], got_y, got_h)
        if where is not None:
            step, signal = where
            return Verification(backend=BACKEND, status="mismatch", compiler=cc, cases_checked=i, mismatch_case=case_id,
                                mismatch_step=step, mismatch_signal=signal,
                                detail=f"case {case_id}: first difference at sample {step} in signal {signal}"), seconds
    return Verification(backend=BACKEND, status="bit_exact", compiler=cc, cases_checked=len(cases),
                        detail=f"{len(cases)} golden vectors replayed through the compiled C99 reference; every output sample "
                               "and every state step equal to the software reference"), seconds
